[workspace]

[package]
name = "three-word-networking"
version = "0.1.0"
edition = "2021"
authors = ["David Irvine <david.irvine@autonomi.com>"]
description = "Convert complex network multiaddrs into memorable three-word combinations with 100% accurate encode/decode"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dirvine/three-word-networking"
readme = "README.md"
keywords = ["networking", "multiaddr", "human-readable", "addressing", "p2p"]
categories = ["network-programming", "command-line-utilities"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4"
hex = "0.4"
bs58 = "0.5"

[[bin]]
name = "three-word-networking"
path = "src/main.rs"

[lib]
name = "three_word_networking"
path = "src/lib.rs"